[package]
name = "cqueue"
version = "0.1.0"
authors = ["timglabisch <tim@ainfach.de>"]

[dependencies]
cdrs = "1.2.0"
time = "*"
rand = "0.4"
rocket = "0.3"
rocket_codegen = "0.3"
r2d2 = "0.7.1"
toml = "0.4"
serde = "*"
serde_derive = "*"

[profile.release]
debug = true